tuner/config/routes.rb
Rails.application.routes.draw do
  # get 'artists'=> 'artists#index'
  # get "artists/:id"=> "artists#show"
  # functionally equivalent w 2 above
  # : create generates new restful route
    # resources :artists, only: [:index, :show, :new, :create, :destroy, :edit, :update]
    # since we have all 7 acttions listed for resources, we only need:
    resources :artists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'artists#index'
end

tuner/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tuner/app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

tuner/app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

tuner/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

tuner/app/controllers/artists_controller.rb
# This is our database query

class ArtistsController < ApplicationController
  # this is called a callback, used to DRY up code, see below
  before_action :set_artist, only: [:show, :destroy, :edit, :update]
  def index
    @artists=Artist.all
  end

  def show
    # @artist = Artist.find(params[:id])
  end

  def new
    @artist=Artist.new
  end

  def create
    @artist = Artist.create(artist_params)
    redirect_to @artist
  end

  def destroy
    # @artist= Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end

  def edit
    # @artist=Artist.find(params[:id])
  end

  def update
    # @artist = Artist.find(params[:id])
    @artist.update(artist_params)
    redirect_to artist_path(@artist)
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :photo_url, :nationality)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end

end

tuner/app/helpers/application_helper.rb
module ApplicationHelper
end

tuner/app/views/artists/edit.html.erb
<h2>Edit Artist</h2>

<%= form_for @artist do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.label :nationality %>
  <%= f.text_field :nationality %>

  <%=f.submit %>

<% end %>

tuner/app/views/artists/index.html.erb
<ul>
  <% @artists.each do |artist|%>
    <li>
      <p><%= link_to artist.name, artist_path(artist) %>
      </p>
      <p>
        <%= link_to 'Delete Artist', artist_path(artist),
        method: :delete,
        data: {confirm: "Are you sure you want to delete this?"} %>
      </p>
    </li>
  <% end %>
</ul>

<h2><%= link_to "Create Artist", new_artist_path %></h2>

tuner/app/views/artists/new.html.erb
<h2>New Artist</h2>
<%= form_for @artist do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.label :nationality %>
  <%= f.text_field :nationality %>

  <%=f.submit %>

<% end %>

tuner/app/views/artists/show.html.erb
<h2><%= link_to "Artists", artists_path %></h2>
<p><%= @artist.name %></p>
<!-- <p><%= @artist.photo_url %></p> -->
<p><%= @artist.nationality %></p>
<img src="<%= @artist.photo_url %>">

<!-- Go to rake routes. then write this w 2 params: what it looks like, wnd where i want to go -->
<h2><%= link_to "Edit this artist", edit_artist_path(@artist) %></h2>

tuner/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tuner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "Tuner", artists_path %></h1>
    </header>
    <%= yield %>
  </body>
  <!-- <footer><p>(c) Jacqui Ahn 2016</p></footer> -->
</html>